### ISSUE TITLE
ImportError, Failed to import my job class

### ISSUE THREAD

**Issue by yaghmr** [seomoz/qless-py#21]
I get an error running ```qless-py-worker```:

```
2015-07-24 10:39:54,152 | PID 1816 | [ERROR] Failed to import mymodule.standardJob.StandardJob
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qless/job.py", line 134, in process
    method = getattr(self.klass, self.queue_name,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qless/job.py", line 117, in __getattr__
    return BaseJob.__getattr__(self, key)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qless/job.py", line 47, in __getattr__
    object.__setattr__(self, 'klass', self._import(self.klass_name))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qless/job.py", line 63, in _import
    mod = __import__(klass.rpartition('.')[0])
ImportError: No module named mymodule.standardJob
```

where ```StandardJob``` is my job class in ```mymodule/standardJob.py``` file.

The job is:

```
client = qless.Client()
q = client.queues['standard']
q.put(StandardJob, {})
```

the ```StandardJob``` class:

```
class StandardJob(object):
    @staticmethod
    def standard(job):
        job.complete()
```

What I miss to do?

**Comment by dlecocq** [comment]
Each of the workers uses a sandbox directory as its working directory. This makes it easy for every job to have some scratch space, as well as provide strong guarantees about temporary files being cleaned up between jobs.

As such, job classes must be importable from these sandbox directories, and so ultimately from anywhere on the system. This could be done in two ways -- 1) installing the job class or 2) appending to `PYTHONPATH` to make it visible to your worker.

**Comment by yaghmr** [comment]
The error is reappeared, I've updated to Python 2.7.12 and to Mac OSX 10.11.6.
I'm still using qless-py 0.10.2 and PYTHONPATH is configured to job directory.

Have you idea of what I've changed?

**Comment by yaghmr** [comment]
Looks like PYTHONPATH in ignored
